### ISSUE TITLE
Could you please share lc_quad_gold.json

### ISSUE THREAD

**Issue by ram-g-athreya** [AskNowQA/SQG#13]
Hi @hamidzafar 

I am trying to replicate your repository locally but I am not able to generate lc_quad_gold.json since the SPARQL endpoint you are using seems to be unavailable. Would it be possible to share this generated dataset so that I would be able to replicate your work.

Thanks

**Comment by hamidzafar** [comment]
Hi, 

You can either setup your own dbpedia SPARQL endpoint or use one of the online versions such as http://dbpedia.org/sparql.

Cheers,
Hamid

**Comment by ram-g-athreya** [comment]
Thanks
