### ISSUE TITLE
Unknown files

### ISSUE THREAD

**Issue by namgiH** [AskNowQA/SQG#15]
Hello.
I tried to run this codes but I found I don't have some files for running, though I downloaded the dataset, model, and bloom filter which you wrote in README.
For example, in orchestrator.Orchestrator.rank, it requires various files for running it.
Some files, for example %s.pt (maybe lcquad.pt?) can be downloaded from your google drive.
And I know stanford-parser.jar is stanford nlp parser file. 
But other cases, for example dataset.vocab, dataset_embed.pth are unknown files, I think.

I found build_vocab function at learning/lstm/scripts/preprocess-lcquad.py,
But I'm not sure it is directly related to dataset.vocab file.
About dataset_embed.pth, I can't find any related codes in this repository.

Would you share those files for me, or tell how to generate those files?
Thanks for reading.

**Comment by hamidzafar** [comment]
Hi, 

Thanks for your interest in this project. 

Unfortunately I don't have the time right to prepare a elaborate scripts to re-produce the results, but I further uploaded the files that you asked for. I hope that it would help.

Cheers,
Hamid

**Comment by namgiH** [comment]
Sorry for late response.
I found the files you mentioned from your google drive.
Thanks a lot!
