### ISSUE TITLE
Requirements.txt

### ISSUE THREAD

**Issue by YaserJaradeh** [AskNowQA/SQG#8]
Creating a Requirements(dependencies) text file at the root of the code would help a lot, specially to dockerize the code
Listing all the Python packages that SQG uses

**Comment by YaserJaradeh** [comment]
Generated requirements.txt file using [pipreqs](https://github.com/bndr/pipreqs) tool
and got this output:
[requirements.txt](https://github.com/AskNowQA/SQG/files/1836871/requirements.txt)

**Comment by hamidzafar** [comment]
Thanks! I had glace at the file you generated and I guess it is not the complete list. I'll update it when I get back from vacation.

**Comment by hamidzafar** [comment]
Pleas checkout https://github.com/AskNowQA/SQG/blob/dev/docker/requirements.txt
